export const styles = {
  container: {
    padding: "24px",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  header: {
    marginBottom: "32px",
    backgroundColor: "#1e293b",
    padding: "20px",
    borderRadius: "12px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.3)",
  },
  headerContent: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerActions: {
    display: "flex",
    gap: "10px",
  },
  title: {
    color: "#e2e8f0",
    margin: 0,
    fontSize: "24px",
    fontWeight: "600",
  },
  subtitle: {
    color: "#94a3b8",
    margin: "8px 0 0 0",
    fontSize: "16px",
  },
  logoutButton: {
    padding: "10px 20px",
    backgroundColor: "#ef4444",
    color: "white",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  cvButton: {
    padding: "10px 20px",
    backgroundColor: "#10b981",
    color: "white",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    minHeight: "100vh",
    gap: "16px",
  },
  loadingSpinner: {
    width: "40px",
    height: "40px",
    border: "4px solid #334155",
    borderTop: "4px solid #6366f1",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
  },
  error: {
    backgroundColor: "#7f1d1d",
    color: "#fecaca",
    padding: "16px",
    borderRadius: "8px",
    margin: "24px auto",
    maxWidth: "600px",
    textAlign: "center" as const,
  },
  emptyState: {
    backgroundColor: "#1e293b",
    padding: "30px",
    borderRadius: "12px",
    textAlign: "center" as const,
    marginTop: "20px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.3)",
  },
  vagasGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: "20px",
  },
  vagaCard: {
    backgroundColor: "#1e293b",
    borderRadius: "12px",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.3)",
    padding: "20px",
    display: "flex",
    flexDirection: "column" as const,
    height: "100%",
  },
  vagaTitulo: {
    fontSize: "18px",
    fontWeight: "600" as const,
    marginBottom: "15px",
    color: "#e2e8f0",
  },
  vagaDetalhes: {
    marginBottom: "15px",
  },
  vagaInfo: {
    color: "#94a3b8",
    margin: "0 0 8px 0",
    fontSize: "14px",
  },
  vagaDescricao: {
    flex: "1",
    marginBottom: "20px",
  },
  inscreverButton: {
    color: "white",
    border: "none",
    padding: "10px 15px",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "500" as const,
    transition: "background-color 0.2s",
  },
  profileButton: {
    padding: "10px 20px",
    backgroundColor: "#6366f1",
    color: "white",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
};
